// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelnetInterceptor.Worker.Data;

#nullable disable

namespace TelnetInterceptor.Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211005805_AddSucursalToCamera")]
    partial class AddSucursalToCamera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Shared.Contracts.Models.AltaEventoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsEventoGuardado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaConectada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrameFin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameInicio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FramePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromFrame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpCamara")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puerto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaCarpeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToFrame")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EventosGuardados");
                });

            modelBuilder.Entity("TelnetInterceptor.Worker.Models.EstadisticasCamara", b =>
                {
                    b.Property<string>("IpCamara")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puerto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaConectada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraUltimoMensaje")
                        .HasColumnType("TEXT");

                    b.Property<int>("MensajesRecibidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCarpeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoMensaje")
                        .HasColumnType("TEXT");

                    b.HasKey("IpCamara", "Puerto");

                    b.ToTable("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
