// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelnetInterceptor.Worker.Data;

#nullable disable

namespace TelnetInterceptor.Worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128220753_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TelnetInterceptor.Worker.Models.EstadisticasCamara", b =>
                {
                    b.Property<string>("IpCamara")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puerto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaConectada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraUltimoMensaje")
                        .HasColumnType("TEXT");

                    b.Property<int>("MensajesRecibidos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCarpeta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoMensaje")
                        .HasColumnType("TEXT");

                    b.HasKey("IpCamara", "Puerto");

                    b.ToTable("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
